### ISSUE TITLE
`Latebind.finalise()` does nothing (leading to crash)

### ISSUE THREAD

**Issue by VolkerH** [mcfletch/pyopengl#35]
There seems to be  a bug in the `Latebind` class. 
I have no clue about pyopengl but was trying to track down an issue:
https://github.com/napari/napari/issues/576#issuecomment-546744529

In the process I found that the exception handler here
https://github.com/mcfletch/pyopengl/blob/139b756389499112e6880fb4ea410529fdcef26c/OpenGL/latebind.py#L44

calls `self.finalise()` to set `self._finalCall()` if it is `None`. However `self.finalise()` doesn't do anything,
see https://github.com/mcfletch/pyopengl/blob/139b756389499112e6880fb4ea410529fdcef26c/OpenGL/latebind.py#L31

**Comment by mcfletch** [comment]
`LateBind` is an abstract base class, it is subclassed to provide the `finalise()` method in `_Alternate` and `Wrapper` classes. A None will be returned when the entry point is not available on the platform. This commonly occurs when you've either used an entry point that isn't available or you've tried to call an entry point before there is an OpenGL Context available.

**Comment by cgohlke** [comment]
I think this issue can be closed. The access violation reported in https://github.com/napari/napari/issues/576#issuecomment-546744529 was due to a wrong row alignment. The `TypeError: 'NoneType' object is not callable` in `latebind.py` was part of the printed traceback but not the cause of the access violation.
